---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dbapp
  namespace: flm
spec:
  serviceName: "mysqldb"
  replicas: 1
  selector:
    matchLabels:
      app: dbapp
  template:
    metadata:
      labels:
        app: dbapp
    spec:
      imagePullSecrets:
        - name: mysecret
      containers:
        - name: dbcont
          image: saidev14/clientapp:dbimage
          ports:
            - containerPort: 3306
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          volumeMounts:
            - name: myvolume
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: myvolume
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 7Gi

